import type { CrudResourceDefinition } from './CrudResource';
import { applyResourceFieldCatalog } from './resourceFieldCatalog';

const baseResourceDefinitions: CrudResourceDefinition[] = [
  {
    key: "departamento", module: "administracion", moduleLabel: "Administración", label: "Departamento",
    table: "administracion.departamento", primaryKey: "id_departamento",
    endpoints: { list: "/api/administracion/departamento", detail: (id: string) => `/api/administracion/departamento/${id}`, create: "/api/administracion/departamento", update: (id: string) => `/api/administracion/departamento/${id}` },
    permissions: "create=ADMINISTRACION.DEPARTAMENTO.CREATE",
    fields: [{ name: "codigo", label: "codigo", type: "text", required: true }, { name: "nombre", label: "nombre", type: "text", required: true }, { name: "descripcion_funciones", label: "descripcion_funciones", type: "textarea" }, { name: "id_departamento_padre", label: "id_departamento_padre", type: "number" }, { name: "id_sucursal", label: "id_sucursal", type: "number" }, { name: "id_jefe_empleado", label: "id_jefe_empleado", type: "number" }, { name: "es_activo", label: "es_activo", type: "checkbox" }, { name: "fecha_inicio", label: "fecha_inicio", type: "date" }, { name: "fecha_fin", label: "fecha_fin", type: "date" }],
  },
  {
    key: "empleado", module: "administracion", moduleLabel: "Administración", label: "Empleado",
    table: "administracion.empleado", primaryKey: "id_empleado",
    endpoints: { list: "/api/administracion/empleado", detail: (id: string) => `/api/administracion/empleado/${id}`, create: "/api/administracion/empleado", update: (id: string) => `/api/administracion/empleado/${id}` },
    permissions: "create=ADMINISTRACION.EMPLEADO.CREATE",
    fields: [{ name: "id_persona", label: "id_persona", type: "number", required: true }, { name: "fecha_ingreso", label: "fecha_ingreso", type: "date", required: true }, { name: "fecha_salida", label: "fecha_salida", type: "date" }, { name: "tipo_contrato", label: "tipo_contrato", type: "select", options: ["INDEFINIDO", "PLAZO_FIJO", "HONORARIOS"] }, { name: "jornada", label: "jornada", type: "select", options: ["FULL_TIME", "PART_TIME"] }, { name: "email_corporativo", label: "email_corporativo", type: "email" }, { name: "telefono_corporativo", label: "telefono_corporativo", type: "text" }, { name: "id_sucursal", label: "id_sucursal", type: "number" }],
  },
  {
    key: "empleado-posicion-pago", module: "administracion", moduleLabel: "Administración", label: "Empleado Posicion Pago",
    table: "administracion.empleado_posicion_pago", primaryKey: "id_empleado_posicion",
    endpoints: { list: "/api/administracion/empleado-posicion-pago", detail: (id: string) => `/api/administracion/empleado-posicion-pago/${id}`, create: "/api/administracion/empleado-posicion-pago", update: (id: string) => `/api/administracion/empleado-posicion-pago/${id}` },
    permissions: "create=ADMINISTRACION.EMPLEADO_POSICION_PAGO.CREATE",
    fields: [{ name: "id_empleado", label: "id_empleado", type: "number", required: true }, { name: "id_posicion", label: "id_posicion", type: "number", required: true }, { name: "vigente_desde", label: "vigente_desde", type: "date" }, { name: "vigente_hasta", label: "vigente_hasta", type: "date" }, { name: "tipo_esquema_pago", label: "tipo_esquema_pago", type: "select", required: true, options: ["SUELDO", "POR_HORA", "COMISION", "MIXTO"] }, { name: "frecuencia_pago", label: "frecuencia_pago", type: "select", options: ["MENSUAL", "QUINCENAL", "SEMANAL"] }, { name: "moneda", label: "moneda", type: "text" }, { name: "pago_por_hora", label: "pago_por_hora", type: "number" }, { name: "sueldo_mensual", label: "sueldo_mensual", type: "number" }, { name: "porcentaje_comision", label: "porcentaje_comision", type: "number" }, { name: "comision_fija", label: "comision_fija", type: "number" }, { name: "tipo_comisionable", label: "tipo_comisionable", type: "textarea" }, { name: "tipo_calculo_comisionable", label: "tipo_calculo_comisionable", type: "textarea" }],
  },
  {
    key: "empleado-registro-pago", module: "administracion", moduleLabel: "Administración", label: "Empleado Registro Pago",
    table: "administracion.empleado_registro_pago", primaryKey: "id_pago",
    endpoints: { list: "/api/administracion/empleado-registro-pago", detail: (id: string) => `/api/administracion/empleado-registro-pago/${id}`, create: "/api/administracion/empleado-registro-pago", update: (id: string) => `/api/administracion/empleado-registro-pago/${id}` },
    permissions: "create=ADMINISTRACION.EMPLEADO_REGISTRO_PAGO.CREATE",
    fields: [{ name: "fecha_pago", label: "fecha_pago", type: "date", required: true }, { name: "haber_basico_pagado", label: "haber_basico_pagado", type: "number" }, { name: "comisiones_totales_pagadas", label: "comisiones_totales_pagadas", type: "number" }, { name: "aguinaldos_totales_pagados", label: "aguinaldos_totales_pagados", type: "number" }, { name: "indemnizacion_total_pagada", label: "indemnizacion_total_pagada", type: "number" }, { name: "otros_cargos_pagados", label: "otros_cargos_pagados", type: "number" }, { name: "descripcion_otros_cargos_pagados", label: "descripcion_otros_cargos_pagados", type: "textarea" }, { name: "notas_pago", label: "notas_pago", type: "textarea" }],
  },
  {
    key: "kpi", module: "administracion", moduleLabel: "Administración", label: "Kpi",
    table: "administracion.kpi", primaryKey: "id_kpi",
    endpoints: { list: "/api/administracion/kpi", detail: (id: string) => `/api/administracion/kpi/${id}`, create: "/api/administracion/kpi", update: (id: string) => `/api/administracion/kpi/${id}` },
    permissions: "create=ADMINISTRACION.KPI.CREATE",
    fields: [{ name: "nombre", label: "nombre", type: "text", required: true }, { name: "descripcion", label: "descripcion", type: "textarea" }, { name: "unidad_medida", label: "unidad_medida", type: "text", required: true }, { name: "frecuencia", label: "frecuencia", type: "text" }],
  },
  {
    key: "objetivo-kpi", module: "administracion", moduleLabel: "Administración", label: "Objetivo Kpi",
    table: "administracion.objetivo_kpi", primaryKey: "id_objetivo_kpi",
    endpoints: { list: "/api/administracion/objetivo-kpi", detail: (id: string) => `/api/administracion/objetivo-kpi/${id}`, create: "/api/administracion/objetivo-kpi", update: (id: string) => `/api/administracion/objetivo-kpi/${id}` },
    permissions: "create=ADMINISTRACION.OBJETIVO_KPI.CREATE",
    fields: [{ name: "id_kpi", label: "id_kpi", type: "number", required: true }, { name: "periodo", label: "periodo", type: "text", required: true }, { name: "valor_meta", label: "valor_meta", type: "number", required: true }, { name: "valor_minimo", label: "valor_minimo", type: "number" }, { name: "valor_maximo", label: "valor_maximo", type: "number" }, { name: "responsable", label: "responsable", type: "number" }, { name: "id_sucursal", label: "id_sucursal", type: "number" }, { name: "id_tienda", label: "id_tienda", type: "number" }, { name: "id_producto", label: "id_producto", type: "number" }, { name: "id_producto_tienda", label: "id_producto_tienda", type: "number" }, { name: "cumplido", label: "cumplido", type: "checkbox" }],
  },
  {
    key: "posicion", module: "administracion", moduleLabel: "Administración", label: "Posicion",
    table: "administracion.posicion", primaryKey: "id_posicion",
    endpoints: { list: "/api/administracion/posicion", detail: (id: string) => `/api/administracion/posicion/${id}`, create: "/api/administracion/posicion", update: (id: string) => `/api/administracion/posicion/${id}` },
    permissions: "create=ADMINISTRACION.POSICION.CREATE",
    fields: [{ name: "codigo", label: "codigo", type: "text", required: true }, { name: "nombre", label: "nombre", type: "text", required: true }, { name: "id_posicion_parent", label: "id_posicion_parent", type: "number" }, { name: "descripcion", label: "descripcion", type: "textarea" }],
  },
  {
    key: "estudiante", module: "personas", moduleLabel: "Personas", label: "Estudiante",
    table: "persona.persona_estudiante", primaryKey: "id_persona",
    endpoints: { list: "/api/personas/estudiante", detail: (id: string) => `/api/personas/estudiante/${id}`, create: "/api/personas/estudiante", update: (id: string) => `/api/personas/estudiante/${id}` },
    permissions: "create=PERSONAS.PERSONA_ESTUDIANTE.CREATE",
    fields: [{ name: "id_persona", label: "id_persona", type: "number", required: true }, { name: "codigo_estudiante", label: "codigo_estudiante", type: "text" }, { name: "id_unidad_educativa", label: "id_unidad_educativa", type: "number" }, { name: "tipo", label: "tipo", type: "text" }, { name: "nivel_actual", label: "nivel_actual", type: "text" }, { name: "curso_actual", label: "curso_actual", type: "text" }, { name: "turno_actual", label: "turno_actual", type: "text" }, { name: "carrera", label: "carrera", type: "text" }, { name: "anio_ingreso", label: "anio_ingreso", type: "number" }],
  },
  {
    key: "estudiante-padre", module: "personas", moduleLabel: "Personas", label: "Estudiante Padre",
    table: "persona.estudiante_padre", primaryKey: "id_asociacion",
    endpoints: { list: "/api/personas/estudiante-padre", detail: (id: string) => `/api/personas/estudiante-padre/${id}`, create: "/api/personas/estudiante-padre", update: (id: string) => `/api/personas/estudiante-padre/${id}` },
    permissions: "create=PERSONAS.ESTUDIANTE_PADRE.CREATE",
    fields: [{ name: "id_padre", label: "id_padre", type: "number", required: true }, { name: "id_estudiante", label: "id_estudiante", type: "number", required: true }],
  },
  {
    key: "padre", module: "personas", moduleLabel: "Personas", label: "Padre",
    table: "persona.persona_padre", primaryKey: "id_padre",
    endpoints: { list: "/api/personas/padre", detail: (id: string) => `/api/personas/padre/${id}`, create: "/api/personas/padre", update: (id: string) => `/api/personas/padre/${id}` },
    permissions: "create=PERSONAS.PERSONA_PADRE.CREATE",
    fields: [{ name: "es_embajador", label: "es_embajador", type: "checkbox" }],
  },
  {
    key: "proveedor", module: "personas", moduleLabel: "Personas", label: "Proveedor",
    table: "persona.proveedor", primaryKey: "id_proveedor",
    endpoints: { list: "/api/personas/proveedor", detail: (id: string) => `/api/personas/proveedor/${id}`, create: "/api/personas/proveedor", update: (id: string) => `/api/personas/proveedor/${id}` },
    permissions: "create=PERSONAS.PROVEEDOR.CREATE",
    fields: [{ name: "nombre_proveedor", label: "nombre_proveedor", type: "text", required: true }, { name: "categoria", label: "categoria", type: "text" }, { name: "telefono", label: "telefono", type: "text" }],
  },
  {
    key: "tutor", module: "personas", moduleLabel: "Personas", label: "Tutor",
    table: "persona.persona_tutor", primaryKey: "id_tutor",
    endpoints: { list: "/api/personas/tutor", detail: (id: string) => `/api/personas/tutor/${id}`, create: "/api/personas/tutor", update: (id: string) => `/api/personas/tutor/${id}` },
    permissions: "create=PERSONAS.PERSONA_TUTOR.CREATE",
    fields: [{ name: "id_persona", label: "id_persona", type: "number", required: true }, { name: "pago_por_hora", label: "pago_por_hora", type: "number", required: true }, { name: "nivel_experiencia", label: "nivel_experiencia", type: "text", required: true }, { name: "tipo_estudiante_especialidad", label: "tipo_estudiante_especialidad", type: "text", required: true }, { name: "nivel_estudiante_especialidad", label: "nivel_estudiante_especialidad", type: "text" }],
  },
  {
    key: "unidad-educativa", module: "personas", moduleLabel: "Personas", label: "Unidad Educativa",
    table: "persona.unidad_educativa", primaryKey: "id_unidad_educativa",
    endpoints: { list: "/api/personas/unidad-educativa", detail: (id: string) => `/api/personas/unidad-educativa/${id}`, create: "/api/personas/unidad-educativa", update: (id: string) => `/api/personas/unidad-educativa/${id}` },
    permissions: "create=PERSONAS.UNIDAD_EDUCATIVA.CREATE",
    fields: [{ name: "nombre", label: "nombre", type: "text", required: true }, { name: "latitud", label: "latitud", type: "number" }, { name: "longitud", label: "longitud", type: "number" }, { name: "categoria", label: "categoria", type: "text", required: true }],
  },
  {
    key: "usuario", module: "personas", moduleLabel: "Personas", label: "Usuario",
    table: "persona.persona_usuario", primaryKey: "id_persona",
    endpoints: { list: "/api/personas/usuario", detail: (id: string) => `/api/personas/usuario/${id}`, create: "/api/personas/usuario", update: (id: string) => `/api/personas/usuario/${id}` },
    permissions: "create=PERSONAS.PERSONA_USUARIO.CREATE",
    fields: [{ name: "id_persona", label: "id_persona", type: "number", required: true }, { name: "nombre_usuario", label: "nombre_usuario", type: "text", required: true }, { name: "contrasena_hash", label: "contrasena_hash", type: "text", required: true }, { name: "tipo_usuario", label: "tipo_usuario", type: "text" }, { name: "es_super_usuario", label: "es_super_usuario", type: "checkbox" }],
  },
  {
    key: "asistencia-clase-curso", module: "servicios_educativos", moduleLabel: "Servicios educativos", label: "Asistencia Clase Curso",
    table: "servicios_educativos.asistencia_clase_curso", primaryKey: "id_asistencia",
    endpoints: { list: "/api/servicios_educativos/asistencia-clase-curso", detail: (id: string) => `/api/servicios_educativos/asistencia-clase-curso/${id}`, create: "/api/servicios_educativos/asistencia-clase-curso", update: (id: string) => `/api/servicios_educativos/asistencia-clase-curso/${id}` },
    permissions: "create=SERVICIOS_EDUCATIVOS.ASISTENCIA_CLASE_CURSO.CREATE",
    fields: [{ name: "id_clase_curso", label: "id_clase_curso", type: "number", required: true }, { name: "id_estudiante", label: "id_estudiante", type: "number", required: true }, { name: "estado_asistencia", label: "estado_asistencia", type: "text", required: true }, { name: "hora_marcacion", label: "hora_marcacion", type: "datetime-local" }, { name: "observaciones", label: "observaciones", type: "textarea" }],
  },
  {
    key: "clase-curso", module: "servicios_educativos", moduleLabel: "Servicios educativos", label: "Clase Curso",
    table: "servicios_educativos.clase_curso", primaryKey: "id_clase_curso",
    endpoints: { list: "/api/servicios_educativos/clase-curso", detail: (id: string) => `/api/servicios_educativos/clase-curso/${id}`, create: "/api/servicios_educativos/clase-curso", update: (id: string) => `/api/servicios_educativos/clase-curso/${id}` },
    permissions: "create=SERVICIOS_EDUCATIVOS.CLASE_CURSO.CREATE",
    fields: [{ name: "id_curso_version", label: "id_curso_version", type: "number", required: true }, { name: "id_aula", label: "id_aula", type: "number" }, { name: "id_tutor", label: "id_tutor", type: "number" }, { name: "fecha", label: "fecha", type: "date", required: true }, { name: "hora_inicio_real", label: "hora_inicio_real", type: "time", required: true }, { name: "hora_fin_real", label: "hora_fin_real", type: "time", required: true }, { name: "estado", label: "estado", type: "text" }, { name: "modalidad", label: "modalidad", type: "text" }, { name: "detalle_temas_revisados", label: "detalle_temas_revisados", type: "textarea" }, { name: "observaciones", label: "observaciones", type: "textarea" }, { name: "motivo_cancelacion", label: "motivo_cancelacion", type: "textarea" }],
  },
  {
    key: "clase-por-hora", module: "servicios_educativos", moduleLabel: "Servicios educativos", label: "Clase Por Hora",
    table: "servicios_educativos.clase_por_hora", primaryKey: "id_clase",
    endpoints: { list: "/api/servicios_educativos/clase-por-hora", detail: (id: string) => `/api/servicios_educativos/clase-por-hora/${id}`, create: "/api/servicios_educativos/clase-por-hora", update: (id: string) => `/api/servicios_educativos/clase-por-hora/${id}` },
    permissions: "create=SERVICIOS_EDUCATIVOS.CLASE_POR_HORA.CREATE",
    fields: [{ name: "id_aula", label: "id_aula", type: "number", required: true }, { name: "id_estudiante", label: "id_estudiante", type: "number", required: true }, { name: "id_tutor", label: "id_tutor", type: "number", required: true }, { name: "id_materia_tree", label: "id_materia_tree", type: "number", required: true }, { name: "hora_llegada", label: "hora_llegada", type: "datetime-local", required: true }, { name: "motivo", label: "motivo", type: "textarea", required: true }, { name: "modalidad", label: "modalidad", type: "textarea" }, { name: "hora_salida", label: "hora_salida", type: "datetime-local" }, { name: "estado_operativo", label: "estado_operativo", type: "textarea" }],
  },
  {
    key: "curso-version", module: "servicios_educativos", moduleLabel: "Servicios educativos", label: "Curso Version",
    table: "servicios_educativos.curso_version", primaryKey: "id_curso_version",
    endpoints: { list: "/api/servicios_educativos/curso-version", detail: (id: string) => `/api/servicios_educativos/curso-version/${id}`, create: "/api/servicios_educativos/curso-version", update: (id: string) => `/api/servicios_educativos/curso-version/${id}` },
    permissions: "create=SERVICIOS_EDUCATIVOS.CURSO_VERSION.CREATE",
    fields: [{ name: "id_producto_educativo", label: "id_producto_educativo", type: "number", required: true }, { name: "nombre_version", label: "nombre_version", type: "text", required: true }, { name: "descripcion_version", label: "descripcion_version", type: "textarea" }, { name: "fecha_inicio", label: "fecha_inicio", type: "date" }, { name: "fecha_fin", label: "fecha_fin", type: "date" }, { name: "precio_version", label: "precio_version", type: "number" }, { name: "id_horario", label: "id_horario", type: "number" }],
  },
  {
    key: "horarios", module: "servicios_educativos", moduleLabel: "Servicios educativos", label: "Horarios",
    table: "servicios_educativos.horarios", primaryKey: "id_horario",
    endpoints: { list: "/api/servicios_educativos/horarios", detail: (id: string) => `/api/servicios_educativos/horarios/${id}`, create: "/api/servicios_educativos/horarios", update: (id: string) => `/api/servicios_educativos/horarios/${id}` },
    permissions: "create=SERVICIOS_EDUCATIVOS.HORARIOS.CREATE",
    fields: [{ name: "repeticion", label: "repeticion", type: "textarea" }, { name: "hora_inicio_lunes", label: "hora_inicio_lunes", type: "time" }, { name: "hora_inicio_martes", label: "hora_inicio_martes", type: "time" }, { name: "hora_inicio_miercoles", label: "hora_inicio_miercoles", type: "time" }, { name: "hora_inicio_jueves", label: "hora_inicio_jueves", type: "time" }, { name: "hora_inicio_viernes", label: "hora_inicio_viernes", type: "time" }, { name: "hora_inicio_sabado", label: "hora_inicio_sabado", type: "time" }, { name: "hora_fin_lunes", label: "hora_fin_lunes", type: "time" }, { name: "hora_fin_martes", label: "hora_fin_martes", type: "time" }, { name: "hora_fin_miercoles", label: "hora_fin_miercoles", type: "time" }, { name: "hora_fin_jueves", label: "hora_fin_jueves", type: "time" }, { name: "hora_fin_viernes", label: "hora_fin_viernes", type: "time" }, { name: "hora_fin_sabado", label: "hora_fin_sabado", type: "time" }],
  },
  {
    key: "materia-tree", module: "servicios_educativos", moduleLabel: "Servicios educativos", label: "Materia Tree",
    table: "servicios_educativos.materia_tree", primaryKey: "id_tree",
    endpoints: { list: "/api/servicios_educativos/materia-tree", detail: (id: string) => `/api/servicios_educativos/materia-tree/${id}`, create: "/api/servicios_educativos/materia-tree", update: (id: string) => `/api/servicios_educativos/materia-tree/${id}` },
    permissions: "create=SERVICIOS_EDUCATIVOS.MATERIA_TREE.CREATE",
    fields: [{ name: "nombre", label: "nombre", type: "text", required: true }, { name: "tema", label: "tema", type: "text", required: true }, { name: "subtema", label: "subtema", type: "text", required: true }],
  },
  {
    key: "paquetes-producto-educativo", module: "servicios_educativos", moduleLabel: "Servicios educativos", label: "Paquetes Producto Educativo",
    table: "servicios_educativos.paquetes_producto_educativo", primaryKey: "id_paquete",
    endpoints: { list: "/api/servicios_educativos/paquetes-producto-educativo", detail: (id: string) => `/api/servicios_educativos/paquetes-producto-educativo/${id}`, create: "/api/servicios_educativos/paquetes-producto-educativo", update: (id: string) => `/api/servicios_educativos/paquetes-producto-educativo/${id}` },
    permissions: "create=SERVICIOS_EDUCATIVOS.PAQUETES_PRODUCTO_EDUCATIVO.CREATE",
    fields: [{ name: "nombre_paquete", label: "nombre_paquete", type: "text", required: true }, { name: "cantidad_horas_paquete", label: "cantidad_horas_paquete", type: "number" }, { name: "precio_paquete", label: "precio_paquete", type: "number", required: true }],
  },
  {
    key: "producto-educativo", module: "servicios_educativos", moduleLabel: "Servicios educativos", label: "Producto Educativo",
    table: "servicios_educativos.producto_educativo", primaryKey: "id_producto_educativo",
    endpoints: { list: "/api/servicios_educativos/producto-educativo", detail: (id: string) => `/api/servicios_educativos/producto-educativo/${id}`, create: "/api/servicios_educativos/producto-educativo", update: (id: string) => `/api/servicios_educativos/producto-educativo/${id}` },
    permissions: "create=SERVICIOS_EDUCATIVOS.PRODUCTO_EDUCATIVO.CREATE",
    fields: [{ name: "nombre", label: "nombre", type: "text", required: true }, { name: "descripcion", label: "descripcion", type: "textarea" }, { name: "tipo_producto", label: "tipo_producto", type: "text", required: true }, { name: "precio_base", label: "precio_base", type: "number" }, { name: "lim_sup_estudiantes", label: "lim_sup_estudiantes", type: "number" }, { name: "lim_inf_estudiantes", label: "lim_inf_estudiantes", type: "number" }, { name: "id_producto_tienda", label: "id_producto_tienda", type: "number" }, { name: "link_bibliografia", label: "link_bibliografia", type: "textarea" }, { name: "link_publicidad", label: "link_publicidad", type: "textarea" }],
  },
  {
    key: "archivos-transaccion", module: "contabilidad", moduleLabel: "Contabilidad", label: "Archivos Transaccion",
    table: "contabilidad.archivos_transaccion", primaryKey: "id_archivo",
    endpoints: { list: "/api/contabilidad/archivos-transaccion", detail: (id: string) => `/api/contabilidad/archivos-transaccion/${id}`, create: "/api/contabilidad/archivos-transaccion", update: (id: string) => `/api/contabilidad/archivos-transaccion/${id}` },
    permissions: "create=CONTABILIDAD.ARCHIVOS_TRANSACCION.CREATE",
    fields: [{ name: "id_transaccion", label: "id_transaccion", type: "number", required: true }, { name: "link_achivo", label: "link_achivo", type: "textarea", required: true }, { name: "link_archivo", label: "link_archivo", type: "textarea" }],
  },
  {
    key: "centro-costo", module: "contabilidad", moduleLabel: "Contabilidad", label: "Centro Costo",
    table: "contabilidad.centro_costo", primaryKey: "id_centro_costo",
    endpoints: { list: "/api/contabilidad/centro-costo", detail: (id: string) => `/api/contabilidad/centro-costo/${id}`, create: "/api/contabilidad/centro-costo", update: (id: string) => `/api/contabilidad/centro-costo/${id}` },
    permissions: "create=CONTABILIDAD.CENTRO_COSTO.CREATE",
    fields: [{ name: "codigo", label: "codigo", type: "text", required: true }, { name: "nombre", label: "nombre", type: "text", required: true }, { name: "id_cuenta_ingreso", label: "id_cuenta_ingreso", type: "number" }, { name: "id_cuenta_costo", label: "id_cuenta_costo", type: "number" }, { name: "observaciones", label: "observaciones", type: "textarea" }],
  },
  {
    key: "centro-costo-mapa", module: "contabilidad", moduleLabel: "Contabilidad", label: "Centro Costo Mapa",
    table: "contabilidad.centro_costo_mapa", primaryKey: "id_cc_mapa",
    endpoints: { list: "/api/contabilidad/centro-costo-mapa", detail: (id: string) => `/api/contabilidad/centro-costo-mapa/${id}`, create: "/api/contabilidad/centro-costo-mapa", update: (id: string) => `/api/contabilidad/centro-costo-mapa/${id}` },
    permissions: "create=CONTABILIDAD.CENTRO_COSTO_MAPA.CREATE",
    fields: [{ name: "id_centro_costo", label: "id_centro_costo", type: "number", required: true }, { name: "tipo", label: "tipo", type: "select", required: true, options: ["DIRECTO", "INDIRECTO"] }, { name: "naturaleza", label: "naturaleza", type: "select", required: true, options: ["FIJO", "VARIABLE"] }, { name: "vigente_desde", label: "vigente_desde", type: "date" }, { name: "vigente_hasta", label: "vigente_hasta", type: "date" }, { name: "id_deuda", label: "id_deuda", type: "number" }, { name: "id_bien", label: "id_bien", type: "number" }, { name: "id_sucursal", label: "id_sucursal", type: "number" }, { name: "id_tienda", label: "id_tienda", type: "number" }, { name: "id_empleado", label: "id_empleado", type: "number" }, { name: "id_posicion", label: "id_posicion", type: "number" }, { name: "id_departamento", label: "id_departamento", type: "number" }],
  },
  {
    key: "concepto-costo", module: "contabilidad", moduleLabel: "Contabilidad", label: "Concepto Costo",
    table: "contabilidad.concepto_costo", primaryKey: "id_concepto",
    endpoints: { list: "/api/contabilidad/concepto-costo", detail: (id: string) => `/api/contabilidad/concepto-costo/${id}`, create: "/api/contabilidad/concepto-costo", update: (id: string) => `/api/contabilidad/concepto-costo/${id}` },
    permissions: "create=CONTABILIDAD.CONCEPTO_COSTO.CREATE",
    fields: [{ name: "codigo", label: "codigo", type: "text", required: true }, { name: "nombre", label: "nombre", type: "text", required: true }, { name: "tipo_concepto", label: "tipo_concepto", type: "text", required: true }, { name: "unidad_medida", label: "unidad_medida", type: "text" }],
  },
  {
    key: "cuenta", module: "contabilidad", moduleLabel: "Contabilidad", label: "Cuenta",
    table: "contabilidad.cuenta", primaryKey: "id_cuenta",
    endpoints: { list: "/api/contabilidad/cuenta", detail: (id: string) => `/api/contabilidad/cuenta/${id}`, create: "/api/contabilidad/cuenta", update: (id: string) => `/api/contabilidad/cuenta/${id}` },
    permissions: "create=CONTABILIDAD.CUENTA.CREATE",
    fields: [{ name: "codigo", label: "codigo", type: "text", required: true }, { name: "nombre_cuenta", label: "nombre_cuenta", type: "text", required: true }, { name: "id_grupo_cuenta", label: "id_grupo_cuenta", type: "number", required: true }],
  },
  {
    key: "cuenta-asignacion", module: "contabilidad", moduleLabel: "Contabilidad", label: "Cuenta Asignacion",
    table: "contabilidad.cuenta_asignacion", primaryKey: "id_cuenta_asignacion",
    endpoints: { list: "/api/contabilidad/cuenta-asignacion", detail: (id: string) => `/api/contabilidad/cuenta-asignacion/${id}`, create: "/api/contabilidad/cuenta-asignacion", update: (id: string) => `/api/contabilidad/cuenta-asignacion/${id}` },
    permissions: "create=CONTABILIDAD.CUENTA_ASIGNACION.CREATE",
    fields: [{ name: "entidad_tipo", label: "entidad_tipo", type: "textarea", required: true }, { name: "id_empleado", label: "id_empleado", type: "number" }, { name: "id_persona_estudiante", label: "id_persona_estudiante", type: "number" }, { name: "id_persona_tutor", label: "id_persona_tutor", type: "number" }, { name: "id_sucursal", label: "id_sucursal", type: "number" }, { name: "id_edificio", label: "id_edificio", type: "number" }, { name: "id_tienda", label: "id_tienda", type: "number" }, { name: "id_bien", label: "id_bien", type: "number" }, { name: "id_deuda", label: "id_deuda", type: "number" }, { name: "id_proveedor", label: "id_proveedor", type: "number" }, { name: "id_departamento", label: "id_departamento", type: "number" }, { name: "id_cuenta", label: "id_cuenta", type: "number", required: true }, { name: "prioridad", label: "prioridad", type: "number" }],
  },
  {
    key: "grupo-cuenta", module: "contabilidad", moduleLabel: "Contabilidad", label: "Grupo Cuenta",
    table: "contabilidad.grupo_cuenta", primaryKey: "id_grupo_cuenta",
    endpoints: { list: "/api/contabilidad/grupo-cuenta", detail: (id: string) => `/api/contabilidad/grupo-cuenta/${id}`, create: "/api/contabilidad/grupo-cuenta", update: (id: string) => `/api/contabilidad/grupo-cuenta/${id}` },
    permissions: "create=CONTABILIDAD.GRUPO_CUENTA.CREATE",
    fields: [{ name: "codigo", label: "codigo", type: "text", required: true }, { name: "nombre", label: "nombre", type: "text", required: true }, { name: "id_parent", label: "id_parent", type: "number" }, { name: "tipo", label: "tipo", type: "text", required: true }, { name: "sub_tipo", label: "sub_tipo", type: "text", required: true }, { name: "sub_grupo", label: "sub_grupo", type: "text" }, { name: "orden_reporte", label: "orden_reporte", type: "number" }],
  },
  {
    key: "pago-tutor", module: "contabilidad", moduleLabel: "Contabilidad", label: "Pago Tutor",
    table: "contabilidad.pago_tutor", primaryKey: "id_pago_tutor",
    endpoints: { list: "/api/contabilidad/pago-tutor", detail: (id: string) => `/api/contabilidad/pago-tutor/${id}`, create: "/api/contabilidad/pago-tutor", update: (id: string) => `/api/contabilidad/pago-tutor/${id}` },
    permissions: "create=CONTABILIDAD.PAGO_TUTOR.CREATE",
    fields: [{ name: "id_tutor", label: "id_tutor", type: "number", required: true }, { name: "periodo_inicio", label: "periodo_inicio", type: "datetime-local", required: true }, { name: "periodo_fin", label: "periodo_fin", type: "datetime-local" }, { name: "estado_pago", label: "estado_pago", type: "textarea" }, { name: "subtotal", label: "subtotal", type: "number" }, { name: "ajustes", label: "ajustes", type: "number" }, { name: "total", label: "total", type: "number" }, { name: "fecha_aprobacion", label: "fecha_aprobacion", type: "datetime-local" }, { name: "fecha_pago", label: "fecha_pago", type: "datetime-local" }, { name: "referencia_pago", label: "referencia_pago", type: "textarea" }, { name: "observacion", label: "observacion", type: "textarea" }],
  },
  {
    key: "pago-tutor-detalle", module: "contabilidad", moduleLabel: "Contabilidad", label: "Pago Tutor Detalle",
    table: "contabilidad.pago_tutor_detalle", primaryKey: "id_pago_tutor_detalle",
    endpoints: { list: "/api/contabilidad/pago-tutor-detalle", detail: (id: string) => `/api/contabilidad/pago-tutor-detalle/${id}`, create: "/api/contabilidad/pago-tutor-detalle", update: (id: string) => `/api/contabilidad/pago-tutor-detalle/${id}` },
    permissions: "create=CONTABILIDAD.PAGO_TUTOR_DETALLE.CREATE",
    fields: [{ name: "id_pago_tutor", label: "id_pago_tutor", type: "number", required: true }, { name: "id_clase", label: "id_clase", type: "number", required: true }, { name: "horas_pasadas", label: "horas_pasadas", type: "number", required: true }, { name: "tarifa_hora_aplicada", label: "tarifa_hora_aplicada", type: "number", required: true }],
  },
  {
    key: "venta-clase", module: "contabilidad", moduleLabel: "Contabilidad", label: "Parte Clases Pasadas",
    table: "contabilidad.venta_clase_batch", primaryKey: "id_venta_clase",
    endpoints: { list: "/api/contabilidad/venta-clase/registrar-batch", detail: (id: string) => `/api/contabilidad/venta-clase/${id}`, create: "/api/contabilidad/venta-clase/registrar-batch", update: (id: string) => `/api/contabilidad/venta-clase/${id}` },
    permissions: "create=CONTABILIDAD.VENTA_CLASE.REGISTRAR_BATCH",
    fields: [
      { name: "fecha", label: "fecha", type: "date", required: true },
      { name: "hora_ingreso", label: "hora_ingreso", type: "time", required: true },
      { name: "hora_salida", label: "hora_salida", type: "time" },
      { name: "nombre_completo_estudiante", label: "nombre_completo_estudiante", type: "text", required: true },
      { name: "tutor", label: "tutor", type: "text", required: true },
      { name: "motivo_clase", label: "motivo_clase", type: "select", options: ["CLASE", "RECUPERACION", "REFORZAMIENTO", "NIVELACION", "EXAMEN", "OTRO"] },
      { name: "materia_producto", label: "materia_producto", type: "text", required: true },
      { name: "tema", label: "tema", type: "textarea" },
      { name: "subtema", label: "subtema", type: "textarea" },
      { name: "efectivo", label: "efectivo", type: "number" },
      { name: "qr", label: "qr", type: "number" },
      { name: "cxc", label: "cxc", type: "number" },
      { name: "paquete", label: "paquete", type: "number" },
      { name: "situacion_base", label: "situacion_base", type: "select", options: ["CLASE_PASADA", "OBSERVADA"] }
    ],
    composite: 'venta-clase-batch',
  },
  {
    key: "transaccion", module: "contabilidad", moduleLabel: "Contabilidad", label: "Transaccion",
    table: "contabilidad.transaccion", primaryKey: "id_transaccion",
    endpoints: { list: "/api/contabilidad/transaccion", detail: (id: string) => `/api/contabilidad/transaccion/${id}`, create: "/api/contabilidad/transaccion", update: (id: string) => `/api/contabilidad/transaccion/${id}` },
    permissions: "create=CONTABILIDAD.TRANSACCION.CREATE",
    fields: [
      { name: "fecha_transaccion", label: "fecha_transaccion", type: "date" },
      { name: "tipo_transaccion", label: "tipo_transaccion", type: "select", required: true, options: ["GENERAL", "COSTO", "VENTA", "BIEN", "DEUDA"] },
      { name: "sub_tipo_transaccion", label: "sub_tipo_transaccion", type: "select" },
      { name: "glosa", label: "glosa", type: "textarea" },
      { name: "id_centro_costo_mapa", label: "id_centro_costo_mapa", type: "number" },
      { name: "id_bien", label: "id_bien", type: "number" },
      { name: "id_movimiento_detalle", label: "id_movimiento_detalle", type: "number" },
      { name: "id_deuda", label: "id_deuda", type: "number" },
      { name: "id_pago_deuda", label: "id_pago_deuda", type: "number" },
      { name: "id_empleado", label: "id_empleado", type: "number" },
      { name: "id_empleado_pago", label: "id_empleado_pago", type: "number" },
      { name: "id_departamento", label: "id_departamento", type: "number" },
      { name: "id_clase_por_hora", label: "id_clase_por_hora", type: "number" },
      { name: "id_producto_educativo", label: "id_producto_educativo", type: "number" },
      { name: "id_curso_version", label: "id_curso_version", type: "number" },
      { name: "id_sucursal", label: "id_sucursal", type: "number" },
      { name: "id_tienda", label: "id_tienda", type: "number" },
      { name: "id_proveedor", label: "id_proveedor", type: "number" },
      { name: "id_dividendo_pago", label: "id_dividendo_pago", type: "number" },
      { name: "id_emision_titulo", label: "id_emision_titulo", type: "number" },
      { name: "id_cliente", label: "id_cliente", type: "number" },
      { name: "id_pago_tutor", label: "id_pago_tutor", type: "number" }
    ], composite: 'transaction-with-account-movements',
  },
  {
    key: "transaccion-movimiento-cuenta", module: "contabilidad", moduleLabel: "Contabilidad", label: "Transaccion Movimiento Cuenta",
    table: "contabilidad.transaccion_movimiento_cuenta", primaryKey: "id_movimiento",
    endpoints: { list: "/api/contabilidad/transaccion-movimiento-cuenta", detail: (id: string) => `/api/contabilidad/transaccion-movimiento-cuenta/${id}`, create: "/api/contabilidad/transaccion-movimiento-cuenta", update: (id: string) => `/api/contabilidad/transaccion-movimiento-cuenta/${id}` },
    permissions: "create=CONTABILIDAD.TRANSACCION_MOVIMIENTO_CUENTA.CREATE",
    fields: [{ name: "id_transaccion", label: "id_transaccion", type: "number", required: true }, { name: "id_cuenta", label: "id_cuenta", type: "number", required: true }, { name: "debe", label: "debe", type: "number" }, { name: "haber", label: "haber", type: "number" }], hideFromNavigation: true,
  },
  {
    key: "deuda", module: "deuda", moduleLabel: "Deuda", label: "Deuda",
    table: "deuda.deuda", primaryKey: "id_deuda",
    endpoints: { list: "/api/deuda/deuda", detail: (id: string) => `/api/deuda/deuda/${id}`, create: "/api/deuda/deuda", update: (id: string) => `/api/deuda/deuda/${id}` },
    permissions: "create=DEUDA.DEUDA.CREATE",
    fields: [{ name: "id_proveedor", label: "id_proveedor", type: "number", required: true }, { name: "monto_inicial", label: "monto_inicial", type: "number", required: true }, { name: "tasa_anual", label: "tasa_anual", type: "number", required: true }, { name: "tipo_tasa", label: "tipo_tasa", type: "text", required: true }, { name: "capitalizacion", label: "capitalizacion", type: "text" }, { name: "plazo_meses", label: "plazo_meses", type: "number", required: true }, { name: "seguro_desgravamen_fijo", label: "seguro_desgravamen_fijo", type: "number" }, { name: "seguro_desgravamen_variable", label: "seguro_desgravamen_variable", type: "number" }, { name: "tipo_calculo_cuotas", label: "tipo_calculo_cuotas", type: "text" }, { name: "frecuencia_cuotas", label: "frecuencia_cuotas", type: "text" }, { name: "tipo_pago", label: "tipo_pago", type: "text" }, { name: "tipo_primer_pago", label: "tipo_primer_pago", type: "text" }, { name: "anualidad_acordada", label: "anualidad_acordada", type: "number" }],
  },
  {
    key: "pago", module: "deuda", moduleLabel: "Deuda", label: "Pago",
    table: "deuda.pago", primaryKey: "id_pago",
    endpoints: { list: "/api/deuda/pago", detail: (id: string) => `/api/deuda/pago/${id}`, create: "/api/deuda/pago", update: (id: string) => `/api/deuda/pago/${id}` },
    permissions: "create=DEUDA.PAGO.CREATE",
    fields: [{ name: "id_deuda", label: "id_deuda", type: "number", required: true }, { name: "fecha_pago", label: "fecha_pago", type: "date" }, { name: "interes_pagado", label: "interes_pagado", type: "number" }, { name: "capital_amortizado", label: "capital_amortizado", type: "number" }, { name: "seguro_desgravamen_pagado", label: "seguro_desgravamen_pagado", type: "number" }, { name: "otros_recargos_pagados", label: "otros_recargos_pagados", type: "number" }, { name: "observaciones", label: "observaciones", type: "textarea" }],
  },
  {
    key: "edificio", module: "infraestructura", moduleLabel: "Infraestructura", label: "Edificio",
    table: "infraestructura.edificio", primaryKey: "id_edificio",
    endpoints: { list: "/api/infraestructura/edificio", detail: (id: string) => `/api/infraestructura/edificio/${id}`, create: "/api/infraestructura/edificio", update: (id: string) => `/api/infraestructura/edificio/${id}` },
    permissions: "create=INFRAESTRUCTURA.EDIFICIO.CREATE",
    fields: [{ name: "id_sucursal", label: "id_sucursal", type: "number", required: true }, { name: "codigo", label: "codigo", type: "text", required: true }, { name: "nombre", label: "nombre", type: "text", required: true }, { name: "direccion_linea1", label: "direccion_linea1", type: "text" }, { name: "ciudad", label: "ciudad", type: "text" }, { name: "departamento", label: "departamento", type: "text" }, { name: "pais", label: "pais", type: "text" }, { name: "latitud", label: "latitud", type: "number" }, { name: "longitud", label: "longitud", type: "number" }, { name: "pisos", label: "pisos", type: "number" }, { name: "largo_m", label: "largo_m", type: "number" }, { name: "ancho_m", label: "ancho_m", type: "number" }, { name: "id_administrador", label: "id_administrador", type: "number" }],
  },
  {
    key: "encargado", module: "infraestructura", moduleLabel: "Infraestructura", label: "Encargado",
    table: "infraestructura.encargado", primaryKey: "id_asignacion",
    endpoints: { list: "/api/infraestructura/encargado", detail: (id: string) => `/api/infraestructura/encargado/${id}`, create: "/api/infraestructura/encargado", update: (id: string) => `/api/infraestructura/encargado/${id}` },
    permissions: "create=INFRAESTRUCTURA.ENCARGADO.CREATE",
    fields: [{ name: "id_sucursal", label: "id_sucursal", type: "number", required: true }, { name: "id_empleado", label: "id_empleado", type: "number", required: true }, { name: "fecha_inicio", label: "fecha_inicio", type: "date", required: true }, { name: "fecha_fin", label: "fecha_fin", type: "date" }],
  },
  {
    key: "espacio", module: "infraestructura", moduleLabel: "Infraestructura", label: "Espacio",
    table: "infraestructura.espacio", primaryKey: "id_espacio",
    endpoints: { list: "/api/infraestructura/espacio", detail: (id: string) => `/api/infraestructura/espacio/${id}`, create: "/api/infraestructura/espacio", update: (id: string) => `/api/infraestructura/espacio/${id}` },
    permissions: "create=INFRAESTRUCTURA.ESPACIO.CREATE",
    fields: [{ name: "id_edificio", label: "id_edificio", type: "number", required: true }, { name: "tipo", label: "tipo", type: "select", required: true, options: ["AULA", "SALA"] }, { name: "categoria_sala", label: "categoria_sala", type: "select", options: ["OFICINA", "CONFERENCIA", "REUNION", "ESPERA", "TIENDA", "OTRA"] }, { name: "tipo_aula", label: "tipo_aula", type: "select", options: ["TEORIA", "LABORATORIO", "COMPUTACION", "MULTIUSO"] }, { name: "es_privada", label: "es_privada", type: "checkbox" }, { name: "nombre", label: "nombre", type: "text" }, { name: "piso", label: "piso", type: "number" }, { name: "capacidad", label: "capacidad", type: "number" }, { name: "largo_m", label: "largo_m", type: "number" }, { name: "ancho_m", label: "ancho_m", type: "number" }, { name: "observaciones", label: "observaciones", type: "textarea" }],
  },
  {
    key: "sucursal", module: "infraestructura", moduleLabel: "Infraestructura", label: "Sucursal",
    table: "infraestructura.sucursal", primaryKey: "id_sucursal",
    endpoints: { list: "/api/infraestructura/sucursal", detail: (id: string) => `/api/infraestructura/sucursal/${id}`, create: "/api/infraestructura/sucursal", update: (id: string) => `/api/infraestructura/sucursal/${id}` },
    permissions: "create=INFRAESTRUCTURA.SUCURSAL.CREATE",
    fields: [{ name: "codigo", label: "codigo", type: "text", required: true }, { name: "nombre", label: "nombre", type: "text", required: true }, { name: "telefono", label: "telefono", type: "text" }, { name: "email", label: "email", type: "email" }, { name: "direccion_linea1", label: "direccion_linea1", type: "text" }, { name: "ciudad", label: "ciudad", type: "text" }, { name: "departamento", label: "departamento", type: "text" }, { name: "pais", label: "pais", type: "text" }, { name: "horario_texto", label: "horario_texto", type: "text" }, { name: "largo_m", label: "largo_m", type: "number" }, { name: "ancho_m", label: "ancho_m", type: "number" }],
  },
  {
    key: "tienda", module: "infraestructura", moduleLabel: "Infraestructura", label: "Tienda",
    table: "infraestructura.tienda", primaryKey: "id_tienda",
    endpoints: { list: "/api/infraestructura/tienda", detail: (id: string) => `/api/infraestructura/tienda/${id}`, create: "/api/infraestructura/tienda", update: (id: string) => `/api/infraestructura/tienda/${id}` },
    permissions: "create=INFRAESTRUCTURA.TIENDA.CREATE",
    fields: [{ name: "id_espacio", label: "id_espacio", type: "number" }, { name: "codigo", label: "codigo", type: "text", required: true }, { name: "nombre", label: "nombre", type: "text", required: true }, { name: "horario_texto", label: "horario_texto", type: "text" }, { name: "id_responsable", label: "id_responsable", type: "number" }],
  },
  {
    key: "bien", module: "inventario", moduleLabel: "Inventario", label: "Bien",
    table: "inventario.bien", primaryKey: "id_bien",
    endpoints: { list: "/api/inventario/bien", detail: (id: string) => `/api/inventario/bien/${id}`, create: "/api/inventario/bien", update: (id: string) => `/api/inventario/bien/${id}` },
    permissions: "create=INVENTARIO.BIEN.CREATE",
    fields: [{ name: "sku", label: "sku", type: "text", required: true }, { name: "nombre", label: "nombre", type: "text", required: true }, { name: "descripcion", label: "descripcion", type: "textarea" }, { name: "tipo", label: "tipo", type: "select", required: true, options: ["MERCADERIA", "MATERIA_PRIMA", "SUMINISTRO", "SERVICIO", "ACTIVO_FIJO"] }, { name: "categoria", label: "categoria", type: "text" }, { name: "subcategoria", label: "subcategoria", type: "text" }, { name: "unidad_compra", label: "unidad_compra", type: "text" }, { name: "unidad_venta", label: "unidad_venta", type: "text" }, { name: "factor_conversion", label: "factor_conversion", type: "number" }, { name: "controla_inventario_loteable", label: "controla_inventario_loteable", type: "checkbox" }, { name: "controla_inventario_no_loteable", label: "controla_inventario_no_loteable", type: "checkbox" }, { name: "metodo_valuacion", label: "metodo_valuacion", type: "select", options: ["PEPS", "UEPS", "PROM"] }, { name: "costo_referencia", label: "costo_referencia", type: "number" }],
  },
  {
    key: "bien-instancia", module: "inventario", moduleLabel: "Inventario", label: "Bien Instancia",
    table: "inventario.bien_instancia", primaryKey: "id_bien_instancia",
    endpoints: { list: "/api/inventario/bien-instancia", detail: (id: string) => `/api/inventario/bien-instancia/${id}`, create: "/api/inventario/bien-instancia", update: (id: string) => `/api/inventario/bien-instancia/${id}` },
    permissions: "create=INVENTARIO.BIEN_INSTANCIA.CREATE",
    fields: [{ name: "id_bien", label: "id_bien", type: "number", required: true }, { name: "descripcion_especificaciones", label: "descripcion_especificaciones", type: "textarea", required: true }, { name: "fecha_compra", label: "fecha_compra", type: "date", required: true }, { name: "id_proveedor_compra", label: "id_proveedor_compra", type: "number" }, { name: "costo_compra", label: "costo_compra", type: "number" }, { name: "precio_compra", label: "precio_compra", type: "number" }, { name: "serial_unico", label: "serial_unico", type: "text" }, { name: "fecha_fabricacion", label: "fecha_fabricacion", type: "date" }, { name: "fecha_vencimiento", label: "fecha_vencimiento", type: "date" }],
  },
  {
    key: "bien-lote", module: "inventario", moduleLabel: "Inventario", label: "Bien Lote",
    table: "inventario.bien_lote", primaryKey: "id_lote",
    endpoints: { list: "/api/inventario/bien-lote", detail: (id: string) => `/api/inventario/bien-lote/${id}`, create: "/api/inventario/bien-lote", update: (id: string) => `/api/inventario/bien-lote/${id}` },
    permissions: "create=INVENTARIO.BIEN_LOTE.CREATE",
    fields: [{ name: "id_bien", label: "id_bien", type: "number", required: true }, { name: "lote_codigo", label: "lote_codigo", type: "text", required: true }, { name: "fecha_compra", label: "fecha_compra", type: "date", required: true }, { name: "id_proveedor_compra", label: "id_proveedor_compra", type: "number" }, { name: "cantidad_compra", label: "cantidad_compra", type: "number", required: true }, { name: "costo_compra_unitario", label: "costo_compra_unitario", type: "number" }, { name: "precio_compra_unitario", label: "precio_compra_unitario", type: "number" }, { name: "fecha_fabricacion", label: "fecha_fabricacion", type: "date" }, { name: "fecha_vencimiento", label: "fecha_vencimiento", type: "date" }],
  },
  {
    key: "movimiento-detalle", module: "inventario", moduleLabel: "Inventario", label: "Movimiento Detalle",
    table: "inventario.movimiento_detalle", primaryKey: "id_movimiento",
    endpoints: { list: "/api/inventario/movimiento-detalle", detail: (id: string) => `/api/inventario/movimiento-detalle/${id}`, create: "/api/inventario/movimiento-detalle", update: (id: string) => `/api/inventario/movimiento-detalle/${id}` },
    permissions: "create=INVENTARIO.MOVIMIENTO_DETALLE.CREATE",
    fields: [{ name: "id_bien", label: "id_bien", type: "number", required: true }, { name: "id_lote", label: "id_lote", type: "number" }, { name: "id_bien_instancia", label: "id_bien_instancia", type: "number" }, { name: "cantidad", label: "cantidad", type: "number" }, { name: "id_espacio_entrada", label: "id_espacio_entrada", type: "number" }, { name: "id_espacio_salida", label: "id_espacio_salida", type: "number" }],
  },
  {
    key: "clase-titulo", module: "societario", moduleLabel: "Societario", label: "Clase Titulo",
    table: "societario.clase_titulo", primaryKey: "id_clase_titulo",
    endpoints: { list: "/api/societario/clase-titulo", detail: (id: string) => `/api/societario/clase-titulo/${id}`, create: "/api/societario/clase-titulo", update: (id: string) => `/api/societario/clase-titulo/${id}` },
    permissions: "create=SOCIETARIO.CLASE_TITULO.CREATE",
    fields: [{ name: "tipo", label: "tipo", type: "select", options: ["ACCION", "CUOTA", "PARTICIPACION", "BONO_CONVERTIBLE", "SAFE", "WARRANT", "OPCION"] }, { name: "sub_tipo", label: "sub_tipo", type: "text", required: true }, { name: "descripcion", label: "descripcion", type: "textarea" }, { name: "valor_nominal", label: "valor_nominal", type: "number" }, { name: "derechos_voto_por_titulo", label: "derechos_voto_por_titulo", type: "number" }, { name: "prioridad_dividendo_bp", label: "prioridad_dividendo_bp", type: "number" }, { name: "pref_liquidacion_x", label: "pref_liquidacion_x", type: "number" }, { name: "es_convertible", label: "es_convertible", type: "checkbox" }, { name: "es_participante", label: "es_participante", type: "checkbox" }],
  },
  {
    key: "dividendo", module: "societario", moduleLabel: "Societario", label: "Dividendo",
    table: "societario.dividendo", primaryKey: "id_dividendo",
    endpoints: { list: "/api/societario/dividendo", detail: (id: string) => `/api/societario/dividendo/${id}`, create: "/api/societario/dividendo", update: (id: string) => `/api/societario/dividendo/${id}` },
    permissions: "create=SOCIETARIO.DIVIDENDO.CREATE",
    fields: [{ name: "id_clase_titulo", label: "id_clase_titulo", type: "number", required: true }, { name: "fecha_declaracion", label: "fecha_declaracion", type: "date", required: true }, { name: "fecha_pago", label: "fecha_pago", type: "date" }, { name: "monto_total", label: "monto_total", type: "number", required: true }, { name: "observaciones", label: "observaciones", type: "textarea" }],
  },
  {
    key: "dividendo-pago", module: "societario", moduleLabel: "Societario", label: "Dividendo Pago",
    table: "societario.dividendo_pago", primaryKey: "id_dividendo_pago",
    endpoints: { list: "/api/societario/dividendo-pago", detail: (id: string) => `/api/societario/dividendo-pago/${id}`, create: "/api/societario/dividendo-pago", update: (id: string) => `/api/societario/dividendo-pago/${id}` },
    permissions: "create=SOCIETARIO.DIVIDENDO_PAGO.CREATE",
    fields: [{ name: "id_dividendo", label: "id_dividendo", type: "number", required: true }, { name: "id_titular", label: "id_titular", type: "number", required: true }, { name: "monto_pagado", label: "monto_pagado", type: "number", required: true }, { name: "fecha_pago_real", label: "fecha_pago_real", type: "date" }],
  },
  {
    key: "emision-titulo", module: "societario", moduleLabel: "Societario", label: "Emision Titulo",
    table: "societario.emision_titulo", primaryKey: "id_emision",
    endpoints: { list: "/api/societario/emision-titulo", detail: (id: string) => `/api/societario/emision-titulo/${id}`, create: "/api/societario/emision-titulo", update: (id: string) => `/api/societario/emision-titulo/${id}` },
    permissions: "create=SOCIETARIO.EMISION_TITULO.CREATE",
    fields: [{ name: "id_clase_titulo", label: "id_clase_titulo", type: "number", required: true }, { name: "ronda", label: "ronda", type: "select", options: ["FOUNDERS", "ANGEL", "SEED", "A", "B", "C", "D", "PUENTE", "OTRA"] }, { name: "instrumento", label: "instrumento", type: "select", options: ["AUMENTO_CAPITAL", "CONVERSION", "PLAN_OPCIONES", "EMISION_SECUNDARIA", "OTRO"] }, { name: "serie", label: "serie", type: "text" }, { name: "fecha_emision", label: "fecha_emision", type: "date", required: true }, { name: "cantidad_autorizada", label: "cantidad_autorizada", type: "number", required: true }, { name: "cantidad_emitida", label: "cantidad_emitida", type: "number", required: true }, { name: "precio_emision", label: "precio_emision", type: "number" }, { name: "observaciones", label: "observaciones", type: "textarea" }],
  },
  {
    key: "tenencia", module: "societario", moduleLabel: "Societario", label: "Tenencia",
    table: "societario.tenencia", primaryKey: "id_tenencia",
    endpoints: { list: "/api/societario/tenencia", detail: (id: string) => `/api/societario/tenencia/${id}`, create: "/api/societario/tenencia", update: (id: string) => `/api/societario/tenencia/${id}` },
    permissions: "create=SOCIETARIO.TENENCIA.CREATE",
    fields: [{ name: "id_emision", label: "id_emision", type: "number", required: true }, { name: "id_titular", label: "id_titular", type: "number", required: true }, { name: "cantidad", label: "cantidad", type: "number", required: true }, { name: "fecha_adquisicion", label: "fecha_adquisicion", type: "date", required: true }, { name: "origen", label: "origen", type: "select", options: ["EMISION", "TRANSFERENCIA", "CONVERSION", "EJERCICIO_OPCION", "AJUSTE"] }, { name: "es_nominativa", label: "es_nominativa", type: "checkbox" }, { name: "observaciones", label: "observaciones", type: "textarea" }],
  },
  {
    key: "titular", module: "societario", moduleLabel: "Societario", label: "Titular",
    table: "societario.titular", primaryKey: "id_titular",
    endpoints: { list: "/api/societario/titular", detail: (id: string) => `/api/societario/titular/${id}`, create: "/api/societario/titular", update: (id: string) => `/api/societario/titular/${id}` },
    permissions: "create=SOCIETARIO.TITULAR.CREATE",
    fields: [{ name: "id_persona", label: "id_persona", type: "number", required: true }, { name: "es_beneficial_owner", label: "es_beneficial_owner", type: "checkbox" }, { name: "observaciones", label: "observaciones", type: "textarea" }],
  },
  {
    key: "transferencia-titulo", module: "societario", moduleLabel: "Societario", label: "Transferencia Titulo",
    table: "societario.transferencia_titulo", primaryKey: "id_transferencia",
    endpoints: { list: "/api/societario/transferencia-titulo", detail: (id: string) => `/api/societario/transferencia-titulo/${id}`, create: "/api/societario/transferencia-titulo", update: (id: string) => `/api/societario/transferencia-titulo/${id}` },
    permissions: "create=SOCIETARIO.TRANSFERENCIA_TITULO.CREATE",
    fields: [{ name: "id_emision", label: "id_emision", type: "number", required: true }, { name: "id_titular_origen", label: "id_titular_origen", type: "number", required: true }, { name: "id_titular_destino", label: "id_titular_destino", type: "number", required: true }, { name: "cantidad", label: "cantidad", type: "number", required: true }, { name: "precio_unitario", label: "precio_unitario", type: "number" }, { name: "fecha_transferencia", label: "fecha_transferencia", type: "date", required: true }, { name: "motivo", label: "motivo", type: "textarea" }],
  },
  {
    key: "permiso", module: "seguridad", moduleLabel: "Seguridad", label: "Permiso",
    table: "seguridad.permiso", primaryKey: "id_permiso",
    endpoints: { list: "/api/seguridad/permiso", detail: (id: string) => `/api/seguridad/permiso/${id}`, create: "/api/seguridad/permiso", update: (id: string) => `/api/seguridad/permiso/${id}` },
    permissions: "",
    fields: [{ name: "codigo", label: "codigo", type: "textarea", required: true }, { name: "descripcion", label: "descripcion", type: "textarea" }, { name: "modulo", label: "modulo", type: "textarea" }],
  },
  {
    key: "rol", module: "seguridad", moduleLabel: "Seguridad", label: "Rol",
    table: "seguridad.rol", primaryKey: "id_rol",
    endpoints: { list: "/api/seguridad/rol", detail: (id: string) => `/api/seguridad/rol/${id}`, create: "/api/seguridad/rol", update: (id: string) => `/api/seguridad/rol/${id}` },
    permissions: "",
    fields: [{ name: "codigo", label: "codigo", type: "textarea", required: true }, { name: "nombre", label: "nombre", type: "textarea", required: true }, { name: "descripcion", label: "descripcion", type: "textarea" }],
  },
  {
    key: "rol-permiso", module: "seguridad", moduleLabel: "Seguridad", label: "Rol Permiso",
    table: "seguridad.rol_permiso", primaryKey: "id_rol", primaryKeys: ["id_rol", "id_permiso"],
    endpoints: { list: "/api/seguridad/rol-permiso", detail: (id: string) => `/api/seguridad/rol-permiso/${id}`, create: "/api/seguridad/rol-permiso", update: (id: string) => `/api/seguridad/rol-permiso/${id}` },
    permissions: "",
    fields: [{ name: "id_rol", label: "id_rol", type: "number", required: true }, { name: "id_permiso", label: "id_permiso", type: "number", required: true }],
  },
  {
    key: "usuario-permiso", module: "seguridad", moduleLabel: "Seguridad", label: "Usuario Permiso",
    table: "seguridad.usuario_permiso", primaryKey: "id_persona", primaryKeys: ["id_persona", "id_permiso"],
    endpoints: { list: "/api/seguridad/usuario-permiso", detail: (id: string) => `/api/seguridad/usuario-permiso/${id}`, create: "/api/seguridad/usuario-permiso", update: (id: string) => `/api/seguridad/usuario-permiso/${id}` },
    permissions: "",
    fields: [{ name: "id_persona", label: "id_persona", type: "number", required: true }, { name: "id_permiso", label: "id_permiso", type: "number", required: true }, { name: "permitido", label: "permitido", type: "checkbox" }],
  },
  {
    key: "usuario-rol", module: "seguridad", moduleLabel: "Seguridad", label: "Usuario Rol",
    table: "seguridad.usuario_rol", primaryKey: "id_persona", primaryKeys: ["id_persona", "id_rol"],
    endpoints: { list: "/api/seguridad/usuario-rol", detail: (id: string) => `/api/seguridad/usuario-rol/${id}`, create: "/api/seguridad/usuario-rol", update: (id: string) => `/api/seguridad/usuario-rol/${id}` },
    permissions: "",
    fields: [{ name: "id_persona", label: "id_persona", type: "number", required: true }, { name: "id_rol", label: "id_rol", type: "number", required: true }],
  },
];

export const resourceDefinitions = applyResourceFieldCatalog(baseResourceDefinitions);

export const resourceModules = Object.values(
  resourceDefinitions.reduce<Record<string, { key: string; label: string; resources: CrudResourceDefinition[] }>>((acc, resource) => {
    if (!acc[resource.module]) acc[resource.module] = { key: resource.module, label: resource.moduleLabel, resources: [] };
    if (!resource.hideFromNavigation) acc[resource.module].resources.push(resource);
    return acc;
  }, {}),
);

export function findResourceModule(module: string | undefined) {
  return resourceModules.find((item) => item.key === module);
}

export function findResourceDefinition(module: string | undefined, resource: string | undefined): CrudResourceDefinition | undefined {
  return resourceDefinitions.find((item) => item.module === module && item.key === resource);
}
